# Generated by Django 3.2 on 2021-05-05 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_post_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='media/solutions')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
