# Generated by Django 3.2 on 2021-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(default='NULL', upload_to='media/solutions'),
        ),
    ]
