# Generated by Django 3.2 on 2021-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20210505_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='receiver',
            field=models.CharField(max_length=100),
        ),
    ]
