# Generated by Django 3.2 on 2021-05-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_solution_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='associated_post_id',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
