# Generated by Django 3.2 on 2021-05-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_solution_associated_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='associated_post_id',
            field=models.IntegerField(),
        ),
    ]
