# Generated by Django 3.2 on 2021-05-08 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0009_alter_solution_associated_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='associated_post_id',
        ),
        migrations.AddField(
            model_name='solution',
            name='associated_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.post'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
