# Generated by Django 3.2 on 2021-05-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_auto_20210508_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='associated_post',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='test_app.post'),
        ),
    ]
