# Generated by Django 3.2 on 2021-05-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_alter_solution_associated_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='associated_post',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='test_app.post'),
        ),
    ]
