# Generated by Django 3.2 on 2021-05-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_alter_solution_associated_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='associated_post',
        ),
    ]
