# Generated by Django 3.2 on 2021-05-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_remove_solution_associated_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='associated_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='test_app.post'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(default=0, upload_to='solutions'),
        ),
    ]
