# Generated by Django 3.2 on 2021-05-10 01:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0018_solution_responded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Vacancy',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='associated_post',
            new_name='associated_vacancy',
        ),
    ]
